spring:
  application:
    name: smartanalytics-server
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jackson.default-property-inclusion: non_null

server:
  port: 8082

management:
  context-path: /management
  security:
    enabled: false

info:
  project:
    artifact: #project.artifactId#
    name: #project.name#
    description: #project.description#
    version: #project.version#
    timestamp: #maven.build-timestamp#
    scmBranch: #scmBranch#
    buildnumber: #buildNumber#

sts:
  audience_name: Multibanking
  secret_claim_property_key: user-secret
  keymanagement.keystore.password: FEDCBA9876543210
  keymanagement.keystore.name: multibanking-keystore
  keymanagement.keystore.alias_prefix: multibanking-
  keymanagement.keystore.type: UBER
  keymanagement.keystore.keys.encKeyPairs.initialCount: 5
  keymanagement.keystore.keys.encKeyPairs.algo: RSA
  keymanagement.keystore.keys.encKeyPairs.sigAlgo: SHA256withRSA
  keymanagement.keystore.keys.encKeyPairs.size: 2048
  keymanagement.keystore.keys.encKeyPairs.name: 'STS Multibanking'
  keymanagement.keystore.keys.encKeyPairs.validityInterval: 3600000
  keymanagement.keystore.keys.encKeyPairs.legacyInterval: 86400000
  keymanagement.keystore.keys.signKeyPairs.initialCount: 5
  keymanagement.keystore.keys.signKeyPairs.algo: RSA
  keymanagement.keystore.keys.signKeyPairs.sigAlgo: SHA256withRSA
  keymanagement.keystore.keys.signKeyPairs.size: 2048
  keymanagement.keystore.keys.signKeyPairs.name: 'STS Multibanking'
  keymanagement.keystore.keys.signKeyPairs.validityInterval: 3600000
  keymanagement.keystore.keys.signKeyPairs.legacyInterval: 86400000
  keymanagement.keystore.keys.secretKeys.initialCount: 5
  keymanagement.keystore.keys.secretKeys.algo: AES
  keymanagement.keystore.keys.secretKeys.size: 256
  keymanagement.keystore.keys.secretKeys.validityInterval: 3600000
  keymanagement.keystore.keys.secretKeys.legacyInterval: 86400000
  keymanagement.rotation.secretKeys.enabled: false
  keymanagement.rotation.signKeyPairs.enabled: false
  keymanagement.rotation.encKeyPairs.enabled: false

---

spring:
  profiles: dev

spring.profiles.include:
  - swagger
  - mongo-persistence

mongo.properties.url: classpath:/mongo.properties

swagger.login.url: http://localhost:8080/auth/realms/multibanking/protocol/openid-connect/auth

sts:
  authservers:
  - name: keycloak
    issUrl: http://localhost:8080/auth/realms/multibanking
    jwksUrl: http://localhost:8080/auth/realms/multibanking/protocol/openid-connect/certs

---

spring:
  profiles: prod

spring.profiles.include:
  - swagger
  - mongo-persistence


