version: "{build}"
image: Visual Studio 2017

skip_tags: true

build:
  verbosity: detailed

platform:
  - x64
  - x86

environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
   # - JAVA_HOME: C:\Program Files\Java\jdk9
   # - JAVA_HOME: C:\Program Files\Java\jdk10

build_script:
  - mvnw.cmd -B spring-javaformat:apply && mvnw.cmd -B -Djna.nosys=true clean test

