version: "{build}"
image: Visual Studio 2017

skip_tags: true

build:
  verbosity: detailed



environment:
  matrix:
  # 64 bit
  - platform: x64
    JAVA_HOME: C:\Program Files\Java\jdk1.8.0
#  - platform: x64
#    JAVA_HOME: C:\Program Files\Java\jdk9
#  - platform: x64
#    JAVA_HOME: C:\Program Files\Java\jdk10
  # 32 bit
  - platform: x86
    JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0

build_script:
  - mvnw.cmd -B spring-javaformat:apply && mvnw.cmd -B -Djna.nosys=true clean test

