# Copyright (c) 2018 Shapelets.io
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

image:
    - Visual Studio 2017
environment:
    AF_PATH: C:\Program Files\ArrayFire\v3
    KHIVA_PATH: C:\Program Files\Khiva\v0
    PATH: $(AF_PATH)\lib;$(KHIVA_PATH)\lib;$(PATH)
    matrix:
        - JAVA_HOME: C:\Program Files\Java\jdk9
        - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
matrix:
    fast_finish: true
cache:
    - C:\Program Files\ArrayFire
    - C:\Program Files\Khiva
clone_folder: C:\khiva-java
platform:
    - x64
before_build:
    - SET PATH=%JAVA_HOME%\bin;%PATH%
    - ps: if(!(Test-Path -Path "C:\Program Files\ArrayFire" )){ appveyor DownloadFile "https://www.dropbox.com/s/ndt1eaouriiu4qi/ArrayFire-v3.5.1.zip?dl=1" -FileName ArrayFire-v3.5.1.zip }
    - ps: if(!(Test-Path -Path "C:\Program Files\ArrayFire" )){ 7z x ArrayFire-v3.5.1.zip -o"C:\Program Files" }
    - reg add HKCU\Software\Kitware\CMake\Packages\ArrayFire /v ArrayFire_CMake_DIR /d "C:\Program Files\ArrayFire\v3\cmake" /f
    - ps: if(!(Test-Path -Path "C:\Program Files\Khiva" )){ appveyor DownloadFile "https://github.com/shapelets/khiva/releases/download/v0.1.0/khiva-v0.1.0-unattended.exe" -FileName khiva-v0.1.0-unattended.exe }
    - ps: if(!(Test-Path -Path "C:\Program Files\Khiva" )){ .\khiva-v0.1.0-unattended.exe /S }
    - start /wait choco install maven
    - java -version
build_script:
    - mvn compile
    - mvn javadoc:javadoc
test_script:
    - mvn test
on_finish:
    - ps: |
        $files = Get-ChildItem -Path .\target\surefire-reports -File -Filter *.xml
        foreach ($file in $files) {
            (New-Object System.Net.WebClient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", $file.FullName)
        }
