language: java

services:
  - mysql

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
#      - mysql-client

dist: trusty

script: 
  - cd PizzApp 
  - mvn clean install -Dmaven.compiler.target=1.8 -Dmaven.compiler.source=1.8

before_install:
  - mysql -e 'CREATE DATABASE pizzappdb;'
  - mysql -e 'USE pizzappdb;'
#  - mysql -u root -e "GRANT ALL PRIVILEGES ON pizzappdb.* TO 'travis'@'%';";

notifications:
  email:
    recipients:
      - gil.maricruz@gmail.com
    on_success: always # default: change
    on_failure: always # default: always
