language: java

services:
  - mysql

build:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - cd PizzApp
#  - mvn clean install -Dmaven.compiler.target=1.8 -Dmaven.compiler.source=1.8
  - mvn clean verify

before_install:
  - mysql -e 'CREATE DATABASE pizzappdb;'
  - mysql -e 'USE pizzappdb;'
#  - mysql -u root -e "GRANT ALL PRIVILEGES ON pizzappdb.* TO 'travis'@'%';";

test:
  - mvn test -B

notifications:
  email:
    recipients:
      - gil.maricruz@gmail.com
    on_success: always # default: change
    on_failure: always # default: always
