language: java
jdk:
  - oraclejdk9
  - oraclejdk8
  - openjdk8  
# do not install anything instead return true via unix command true
install: true
script: mvn clean test
notifications:
  email:
    - github@graphhopper.com

# enable container-based stack
sudo: false
