language: java
dist: trusty
sudo: false

jdk:
  - openjdk8
  - oraclejdk8
  - oraclejdk9
  - oraclejdk10
  - oraclejdk-ea
matrix:
  allow_failures:
    - jdk: oraclejdk-ea
  fast_finish: true

cache:
  directories:
    - $HOME/.m2

install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - mvn -Dsurefire.useFile=false jacoco:prepare-agent test jacoco:report
after_script:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./cc-test-reporter format-coverage -t jacoco target/site/jacoco/jacoco.xml; fi
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./cc-test-reporter upload-coverage; fi

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/endpoint/c6cc872b193cbad86273/529f9078ed5ab0b3bf04ef9a/
