language: java
jdk:
  - oraclejdk8
  - openjdk8
env:
  # NIO + No SSL
  - NIO_ENABLED=true   EPOLL_ENABLED=false  NO_SSL_ENABLED=true   SSL_JDK_ENABLED=false  SSL_OPENSSL_ENABLED=false
  # NIO + No SSL + Logging disabled
  - NIO_ENABLED=true   EPOLL_ENABLED=false  NO_SSL_ENABLED=true   SSL_JDK_ENABLED=false  SSL_OPENSSL_ENABLED=false  LOG_LEVEL=OFF
  # NIO + JDK SSL
  - NIO_ENABLED=true   EPOLL_ENABLED=false  NO_SSL_ENABLED=false  SSL_JDK_ENABLED=true   SSL_OPENSSL_ENABLED=false
  # NIO + OpenSSL
  - NIO_ENABLED=true   EPOLL_ENABLED=false  NO_SSL_ENABLED=false  SSL_JDK_ENABLED=false  SSL_OPENSSL_ENABLED=true
  # Epoll + No SSL
  - NIO_ENABLED=false  EPOLL_ENABLED=true   NO_SSL_ENABLED=true   SSL_JDK_ENABLED=false  SSL_OPENSSL_ENABLED=false
  # Epoll + JDK SSL
  - NIO_ENABLED=false  EPOLL_ENABLED=true   NO_SSL_ENABLED=false  SSL_JDK_ENABLED=true   SSL_OPENSSL_ENABLED=false
  # Epoll + OpenSSL
  - NIO_ENABLED=false  EPOLL_ENABLED=true   NO_SSL_ENABLED=false  SSL_JDK_ENABLED=false  SSL_OPENSSL_ENABLED=true

services:
  - docker

cache:
  directories:
    - $HOME/.m2

before_install:
  - 'chmod +x mvnw'
  - 'docker-compose up -d'

install: true

script:
  - 'rm -rf $HOME/.m2/repository/io/hekate'
  - './mvnw -B clean install'

after_success:
  - 'bash <(curl -s https://codecov.io/bash)'

branches:
  except:
  - /experimental-.*/

notifications:
  slack: hekate-io:tSiGS0Suj7vrmJN0tlTXw9xn
