# Run using docker, not a VM
sudo: false

# Cache maven downloaded packages
cache:
  directories:
    - $HOME/.m2

# Now the actual core of the script
language: java

# Send notifs to slack
notifications:
  slack:
    secure: "XaNxhYbbrztejHuhjhodN50oPeb5uNsGusXs1Ty0/g/FueesqT2PRbk7xhsb0ewnPzPnkPogk4ksSDiNJjPa0RHcrYPHLkv3tDY7kxeA2+awJV9chTpcVg3RjB+ts8/XU1pq/qHw+g6t7ylhdadBkj9NSRgb/1H+kTz8fu9CvsoneaiVLd75JUq3Pk/Aw6R/91Xp9erO6ZDSuYJPDbG6Qr2QST1e+VyrBtuhniY9cFy1GgsSSnTzUOqp4tHle6Sen56I8pGYWsl+Bb71vmgxCKWoSXk5xwMdO4AMIfJO9PzEhZgJpnb3XowIhx4oG01jzmCsuzdsg4l+2nUCtYG30I9x0kFtfvqFzjXk0jRK83pCFPQvk5P/pdrvYcsp52tlewNHhHqeCXIlqc3oWx299sMvIyhLkhHku8YVtafavZbP3e6cUNLXr3RIzFbwM8q5eDf0GNGhazb14InMBNGACKkhYmm0a+XF6i+QI44lVX2P1TvkWg69m5erEVH2BvKp45SBHygRuGX/6Qx2loVTcP1NqXfvrDRIrOhjbL+RyVMDT9bQdrJFhCgQrPUBu7RqdC20jAcSoBaLDyf66Q9qz27KEHRUMbzFlyprvGLb3/AB6W3Z2nI0Js4C1tCXxRe1hUBYQVGTHPrBiNpJnuOX35Cn9eT0QhLBHBNj+p4Ahv8="
