language : java
script :
    - cd core
    - sed s/GRAPHIC_ENABLE\ =\ true// src/test/resources/kraken-test.conf -i
    - mvn install
    - cd ../examples
    - ant
jdk : oraclejdk8
branches :
    except: mvn-repo
notifications:
    slack: intech-sudparis:Z3xKQEmZT2a9BFBqouokQ6J7
    on_success: change
    on_failure: always
    email : false
