# Snowizard-specific options.
snowizard:

  datacenterId: ${DW_DATACENTER_ID:-1}
  workerId: ${DW_WORKER_ID:-1}
  enabled: true

# Swagger-specific options.
swagger:

  resourcePackage: com.smoketurner.notification.application.resources
  title: Notification API
  version: v1
  description: Notification service API
  contact: jplock@smoketurner.com
  license: Apache 2.0
  licenseUrl: https://www.apache.org/licenses/LICENSE-2.0

# Riak-specific options.
riak:

  nodes:
    - 127.0.0.1:8087

# HTTP-specific options.
server:

  type: simple
  applicationContextPath: /
  connector:
    type: http
    port: ${PORT:-8080}

  requestLog:
    appenders:
      - type: console
        timeZone: UTC
        target: stdout

logging:
  level: INFO
  loggers:
    com.smoketurner.notification: DEBUG
    com.basho.riak: INFO
  appenders:
    - type: console
      timeZone: UTC
      target: stdout
