version: '2.3'
services:

  kibana:
    image: docker.elastic.co/kibana/kibana:5.5.3
    restart: always
    environment:
      - ELASTICSEARCH_URL=http://es:9200
      - xpack.security.enabled=false
    ports:
      - 5601:5601
    depends_on:
      - es      

  job-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      CLOUD_CONFIG_FIND_LABEL: $CLOUD_CONFIG_FIND_LABEL
      SPRING_PROFILES_ACTIVE: dev
    image: leonardobonacci/oogway-job-service
    restart: always
    depends_on:
      config-service:
        condition: service_healthy
    ports:
      - 8765:8765

  localtimer-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      CLOUD_CONFIG_FIND_LABEL: $CLOUD_CONFIG_FIND_LABEL
      SPRING_PROFILES_ACTIVE: dev
    image: leonardobonacci/oogway-localtimer-service
    restart: always
    depends_on:
      rabbit:
        condition: service_started
      config-service:
        condition: service_healthy
    ports:
      - 6666:6666

  money-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      CLOUD_CONFIG_FIND_LABEL: $CLOUD_CONFIG_FIND_LABEL
      SPRING_PROFILES_ACTIVE: dev
    image: leonardobonacci/oogway-money-service
    restart: always
    depends_on:
      rabbit:
        condition: service_started
      config-service:
        condition: service_healthy
    ports:
      - 11111:11111

  sentiment-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      CLOUD_CONFIG_FIND_LABEL: $CLOUD_CONFIG_FIND_LABEL
      SPRING_PROFILES_ACTIVE: dev
    image: leonardobonacci/oogway-sentiment-service
    restart: always
    depends_on:
      rabbit:
        condition: service_started
      config-service:
        condition: service_healthy
    ports:
      - 7777:7777

  weather-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      CLOUD_CONFIG_FIND_LABEL: $CLOUD_CONFIG_FIND_LABEL
      SPRING_PROFILES_ACTIVE: dev
    image: leonardobonacci/oogway-weather-service
    restart: always
    depends_on:
      rabbit:
        condition: service_started
      config-service:
        condition: service_healthy
    ports:
      - 9999:9999

  zipkin:
    environment:
      STORAGE_TYPE: elasticsearch
      ES_HOSTS: es
    image: openzipkin/zipkin:2.5
    restart: always
    ports:
      - 9411:9411

#  tor: 
#    image: osminogin/tor-simple
#    ports:
#      - 127.0.0.1:9050:9050 