name: BSkyBlock
main: us.tastybento.bskyblock.BSkyBlock
version: ${version}

authors: [tastybento, Poslovitch]

softdepend: [Herochat, DeluxeChat, PlaceholderAPI, MVdWPlaceholderAPI]

load: startup
loadbefore: [Multiverse-Core]

permissions:    
  bskyblock.*:
    default: false
    children:
      bskyblock.island.*:
        children:
          bskyblock.island:
           description: Allow island command usage
           default: true
          bskyblock.island.create:
            description: Allow island creation
            default: true
          bskyblock.island.home:
            description: Allow teleporting to player island
            default: true
          bskyblock.island.reset:
            description: Player can use the island reset or restart command
            default: true  
          bskyblock.island.sethome:
            description: Let the player use the sethome command
            default: true
          bskyblock.island.info:
            description: Let the player check their island level
            default: true
          bskyblock.island.sethome:
            description: Let the player set their island teleport point
            default: true
          bskyblock.island.controlpanel:
            description: Allows usage of the island GUI
            default: true
          bskyblock.island.lock:
            description: Allows island locking
            default: false
          bskyblock.island.expel:
            description: Allows expelling of visitors
            default: true
          bskyblock.island.ban:
            description: Allows banning of visitors
            default: false
          bskyblock.island.settings:
            description: Player can see server settings
            default: true
          bskyblock.island.lang:
            description: Player can select a language
            default: true
          bskyblock.island.name:
            description: Player can set the name of their island
            default: true
          bskyblock.island.spawn:
            description: Player can use the island spawn command if spawn exists
            default: true
          bskyblock.island.reset:
            description: Player can use the island reset or restart command
            default: true  
          bskyblock.island.team:
            description: Let a player use team commands
            default: true
      bskyblock.mod.*:
        children:
          bskyblock.mod.info:
            description: Let a moderator see info on a player
            default: op
          bskyblock.mod.resethome:
            description: Allows setting or reseting of a player's home position
            default: op
          bskyblock.mod.clearreset:
            description: Allow clearing of island reset limit
            default: false
          bskyblock.mod.tp:
            description: Allows teleport to an island
            default: op
          bskyblock.mod.bypassprotect:
            description: Allow moderator to bypass island protection
            default: op
          bskyblock.mod.bypassexpel:
            description: Allow moderator to bypass island expulsion
            default: op
          bskyblock.mod.topbreeders:
            description: Lists most populated islands current loaded
            default: op
          bskyblock.mod.lock:
            description: Locks or unlocks an island
            default: op
          bskyblock.mod.bypasslock:
            description: Bypasses an island lock
            default: op
          bskyblock.mod.team:
            description: Enables modification of teams via kick and add commands
            default: false
          bskyblock.mod.name:
            description: Enables naming of player's islands
            default: false
          bskyblock.mod.resetname:
            description: Enables reset of player's island names
            default: false
      bskyblock.admin.*:
        children:
          bskyblock.admin.clearresetall:
            description: Allow clearing of island reset limit of all players
            default: op
          bskyblock.admin.reload:
            description: Reload the config.yml
            default: op
          bskyblock.admin.delete:
            description: Let a player completely remove a player (including island)
            default: op
          bskyblock.admin.deleteisland:
            description: Let a player completely remove the island the player is on
            default: op
          bskyblock.admin.register:
            description: Let a player register the nearest island to another player.
            default: op
          bskyblock.admin.unregister:
            description: Removes a player from an island without deleting the island blocks.
            default: op
          bskyblock.admin.purge:
            description: Let a player purge old islands.
            default: op
          bskyblock.admin.setspawn:
            description: Allows use of spawn tools
            default: op
          bskyblock.admin.setrange:
            description: Allows setting of island protection range
            default: op
          bskyblock.admin.topbreeders:
            description: Lists most populated islands current loaded
            default: op
          bskyblock.admin.reserve:
            description: Reserves an empty spot for a player's next island
            default: op
          bskyblock.admin.settingsreset:
            description: Resets all the islands to default protection settings
            default: op
          bskyblock.admin.noban:
            description: Player cannot be banned from an island
            default: op
          bskyblock.admin.setlanguage:
            description: Resets all player languages and sets the default language
            default: op