before:
  - description: Pull down and Configure the variables for our Singularity Deployment
    commands:
       - git clone git@git.hubteam.com:HubSpot/SingularityBuildConfig.git custom-build-config
       - /bin/bash custom-build-config/setup-ui-env.sh

after:
  onSuccess:
    - description:
      name: publish
      activeByDefault: false
      commands:
        - sleep 600
        - /bin/bash custom-build-config/publish-ui.sh


stepActivation:
  publish:
    branches: [staging, build-on-blazar]


