server:
  port: 9099
spring:
    datasource:
      url: jdbc:postgresql://localhost:5432/aerodev
      username: cruder
      password: p@ssw0rd
    flyway:
            url: jdbc:postgresql://localhost:5432/aerodev
            user: cruder
            password: p@ssw0rd
            sql-migration-separator: __
            schemas: aero
            locations: classpath:db/migration/postgresql