spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost/users}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        ddl-auto: update
        temp:
          use_jdbc_metadata_defaults: false
logging:
  level:
    org:
      springframework: info
server:
  port: 8081

security:
  oauth2:
    client:
       clientId: ${GIT_CLIENT_ID}
       clientSecret: ${GIT_CLIENT_SECRET}
       accessTokenUri: https://github.com/login/oauth/access_token
       userAuthorizationUri: https://github.com/login/oauth/authorize
       clientAuthenticationScheme: form
    resource:
       userInfoUri: https://api.github.com/user
    authorization:
      realm: Monopoly in map
