server:
  port: 5000

spring:
  datasource:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: true

thymeleaf:
  cache: false
  check-template: true
  check-template-location: true
  content-type: text/html
  enabled: true
  encoding: UTF-8
  mode: HTML
  prefix: classpath:/templates/
  suffix: .html

logging:
  level:
    org.hibernate.tool.hbm2ddl: debug
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
    org.springframework.web: trace

liquibase:
  change-log: classpath:/db/changelog-master.xml

auth:
  admin:
    username: admin
    password: 123