swagger: '2.0'
info:
  description: Api Documentation
  version: '1.0'
  title: Api Documentation
  termsOfService: 'urn:tos'
  contact: {}
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0'
host: 'localhost:8081'
basePath: /
tags:
  - name: seminar-endpoint
    description: Seminar Endpoint
  - name: method-endpoint
    description: Method Endpoint
paths:
  /api/methods:
    get:
      tags:
        - method-endpoint
      summary: getAllMethods
      operationId: getAllMethodsUsingGET
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: X-User-ID
          in: header
          description: X-User-ID
          required: false
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Method'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    post:
      tags:
        - method-endpoint
      summary: createMethod
      operationId: createMethodUsingPOST
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: X-User-ID
          in: header
          description: X-User-ID
          required: true
          type: string
        - in: body
          name: methodResource
          description: methodResource
          required: true
          schema:
            $ref: '#/definitions/MethodResource'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/MethodResource'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /api/methods/levels:
    get:
      tags:
        - method-endpoint
      summary: getAllMethodLevels
      operationId: getAllMethodLevelsUsingGET
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/MethodLevel'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    post:
      tags:
        - method-endpoint
      summary: createMethodLevel
      operationId: createMethodLevelUsingPOST
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: methodLevelResource
          description: methodLevelResource
          required: true
          schema:
            $ref: '#/definitions/MethodLevelResource'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/MethodLevelResource'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  '/api/methods/levels/{methodLevelId}':
    put:
      tags:
        - method-endpoint
      summary: updateMethodLevel
      operationId: updateMethodLevelUsingPUT
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: methodLevelId
          in: path
          description: methodLevelId
          required: true
          type: string
        - in: body
          name: methodLevelResource
          description: methodLevelResource
          required: true
          schema:
            $ref: '#/definitions/MethodLevelResource'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/MethodLevelResource'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /api/methods/types:
    get:
      tags:
        - method-endpoint
      summary: getAllMethodTypes
      operationId: getAllMethodTypesUsingGET
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/MethodType'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    post:
      tags:
        - method-endpoint
      summary: createMethodType
      operationId: createMethodTypeUsingPOST
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: methodTypeResource
          description: methodTypeResource
          required: true
          schema:
            $ref: '#/definitions/MethodTypeResource'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/MethodTypeResource'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  '/api/methods/types/{methodTypeId}':
    put:
      tags:
        - method-endpoint
      summary: updateMethodType
      operationId: updateMethodTypeUsingPUT
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: methodTypeId
          in: path
          description: methodTypeId
          required: true
          type: string
        - in: body
          name: methodTypeResource
          description: methodTypeResource
          required: true
          schema:
            $ref: '#/definitions/MethodTypeResource'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/MethodTypeResource'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  '/api/methods/{methodId}':
    get:
      tags:
        - method-endpoint
      summary: getMethod
      operationId: getMethodUsingGET
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: methodId
          in: path
          description: methodId
          required: true
          type: string
        - name: X-User-ID
          in: header
          description: X-User-ID
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/MethodResource'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    put:
      tags:
        - method-endpoint
      summary: updateMethod
      operationId: updateMethodUsingPUT
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: methodId
          in: path
          description: methodId
          required: true
          type: string
        - name: X-User-ID
          in: header
          description: X-User-ID
          required: true
          type: string
        - in: body
          name: methodResource
          description: methodResource
          required: true
          schema:
            $ref: '#/definitions/MethodResource'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/MethodResource'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    delete:
      tags:
        - method-endpoint
      summary: deleteMethod
      operationId: deleteMethodUsingDELETE
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: methodId
          in: path
          description: methodId
          required: true
          type: string
        - name: X-User-ID
          in: header
          description: X-User-ID
          required: true
          type: string
      responses:
        '200':
          description: OK
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  /api/seminars/goals:
    get:
      tags:
        - seminar-endpoint
      summary: getSeminarGoals
      operationId: getSeminarGoalsUsingGET
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: seminarType
          in: query
          description: seminarType
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/SeminarGoal'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    post:
      tags:
        - seminar-endpoint
      summary: createSeminarGoal
      operationId: createSeminarGoalUsingPOST
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: seminarGoalResource
          description: seminarGoalResource
          required: true
          schema:
            $ref: '#/definitions/SeminarGoalResource'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/SeminarGoalResource'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  '/api/seminars/goals/{seminarGoalId}':
    put:
      tags:
        - seminar-endpoint
      summary: updateSeminarGoal
      operationId: updateSeminarGoalUsingPUT
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: seminarGoalId
          in: path
          description: seminarGoalId
          required: true
          type: string
        - in: body
          name: seminarGoalResource
          description: seminarGoalResource
          required: true
          schema:
            $ref: '#/definitions/SeminarGoalResource'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/SeminarGoalResource'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /api/seminars/types:
    get:
      tags:
        - seminar-endpoint
      summary: getSeminarTypes
      operationId: getSeminarTypesUsingGET
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/SeminarType'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    post:
      tags:
        - seminar-endpoint
      summary: createSeminarType
      operationId: createSeminarTypeUsingPOST
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: seminarTypeResource
          description: seminarTypeResource
          required: true
          schema:
            $ref: '#/definitions/SeminarTypeResource'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/SeminarTypeResource'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  '/api/seminars/types/{seminarTypeId}':
    put:
      tags:
        - seminar-endpoint
      summary: updateSeminarType
      operationId: updateSeminarTypeUsingPUT
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: seminarTypeId
          in: path
          description: seminarTypeId
          required: true
          type: string
        - in: body
          name: seminarTypeResource
          description: seminarTypeResource
          required: true
          schema:
            $ref: '#/definitions/SeminarTypeResource'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/SeminarTypeResource'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
definitions:
  Attachment:
    type: object
    properties:
      content:
        type: string
      created_at:
        type: string
        example: 'yyyy-MM-dd''T''HH:mm:ss.SSSz'
      created_by:
        $ref: '#/definitions/User'
      id:
        type: string
      modified_at:
        type: string
        example: 'yyyy-MM-dd''T''HH:mm:ss.SSSz'
      modified_by:
        $ref: '#/definitions/User'
  Method:
    type: object
    properties:
      attachments:
        type: array
        items:
          $ref: '#/definitions/Attachment'
      content:
        type: string
      created_at:
        type: string
        format: date-time
      created_by:
        $ref: '#/definitions/User'
      id:
        type: string
      method_levels:
        type: array
        items:
          $ref: '#/definitions/MethodLevel'
      method_types:
        type: array
        items:
          $ref: '#/definitions/MethodType'
      modified_at:
        type: string
        format: date-time
      modified_by:
        $ref: '#/definitions/User'
      seminar_goals:
        type: array
        items:
          $ref: '#/definitions/SeminarGoal'
      seminar_type:
        $ref: '#/definitions/SeminarType'
      title:
        type: string
  MethodLevel:
    type: object
    properties:
      description:
        type: string
      id:
        type: string
      name:
        type: string
  MethodLevelResource:
    type: object
    properties:
      description:
        type: string
      id:
        type: string
      name:
        type: string
  MethodResource:
    type: object
    properties:
      attachments:
        type: array
        items:
          $ref: '#/definitions/Attachment'
      content:
        type: string
      created_at:
        type: string
        format: date-time
      created_by:
        $ref: '#/definitions/User'
      id:
        type: string
      method_levels:
        type: array
        items:
          $ref: '#/definitions/MethodLevel'
      method_types:
        type: array
        items:
          $ref: '#/definitions/MethodType'
      modified_at:
        type: string
        format: date-time
      modified_by:
        $ref: '#/definitions/User'
      seminar_goals:
        type: array
        items:
          $ref: '#/definitions/SeminarGoal'
      seminar_type:
        $ref: '#/definitions/SeminarType'
      title:
        type: string
  MethodType:
    type: object
    properties:
      description:
        type: string
      id:
        type: string
      name:
        type: string
  MethodTypeResource:
    type: object
    properties:
      description:
        type: string
      id:
        type: string
      name:
        type: string
  SeminarGoal:
    type: object
    properties:
      description:
        type: string
      id:
        type: string
      name:
        type: string
      seminar_type:
        $ref: '#/definitions/SeminarType'
  SeminarGoalResource:
    type: object
    properties:
      description:
        type: string
      id:
        type: string
      name:
        type: string
      seminar_type:
        $ref: '#/definitions/SeminarType'
  SeminarType:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      seminar_goals:
        type: array
        items:
          $ref: '#/definitions/SeminarGoal'
  SeminarTypeResource:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      seminar_goals:
        type: array
        items:
          $ref: '#/definitions/SeminarGoal'
  User:
    type: object
    properties:
      id:
        type: string
      role:
        type: string
        enum:
          - ADMIN
          - EDITOR
          - WRITER
          - READER