version: 2
jobs:
  build:
    working_directory: ~/dropwizard
    environment:
      JAVA_TOOL_OPTIONS: -Xms512m -Xmx2g
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
          key: dropwizard-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: dropwizard-{{ checksum "pom.xml" }}
      - run: mvn package
      - store_test_results:
          path: target/surefire-reports
