---
apiVersion: v1
kind: Route
metadata:
  labels:
    app: hono-adapter-amqp-vertx
    provider: fabric8
    version: "${project.version}"
    group: ${project.groupId}
  name: hono-adapter-amqp-vertx-sec
spec:
  port:
    targetPort: 4041
  tls:
    termination: passthrough
  to:
    kind: Service
    name: hono-adapter-amqp-vertx
