# MySQL config described here:
# https://springframework.guru/configuring-spring-boot-for-mysql
spring.h2.console.enabled: false

# NOTE: If this was actually a production database, you not tell Hibernate
# to use the create-drop option. This tells Hibernate to recreate the database on startup.
# Definitely not the behavior we want.
# You can set this property to the following values:
# none, validate, update, create-drop.
# If this was actually a production database, you probably would want to use validate.
#spring.jpa.hibernate.ddl-auto: create-drop
spring.jpa.hibernate.ddl-auto: update

spring.http.multipart.max-file-size: 500MB
spring.http.multipart.max-request-size: 500MB

management.security.enabled: true
management.context-path: /admin/

spring.jpa.properties.hibernate.generate_statistics: false
spring.jpa.show-sql: false


app.admin.username: "admin"
app.admin.password: "adminpassword"

cgu-url: "https://www.dailymotion.com/embed/video/k12tO5H7YXMWlTnNXly"

spring:
  mail:
    host: mailhost.rd.francetelecom.fr
    port: 2525

