### Spring properties
# Service registers under this name
spring:
  application:
    name: repo-ms

# Discovery Server Access
eureka:
  instance:
    metadataMap:
      type: repo
      friendlyname: Hadoop
    hostName: ${REPO_PUBLISH_HOST:localhost} 
    preferIpAddress: false 
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVICE_HOST:localhost}:${EUREKA_SERVICE_PORT:8761}/eureka/

# HTTP Server (Tomcat) Port
server: 
  port: ${REPO_PUBLISH_PORT:2300}

# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
error:
  whitelabel:
    enabled: false
    
hadoop:    
  hostserver: ${HADOOP_HOSTSERVER:localhost}
  port: ${HADOOP_PORT:50070}