gui:
  title: Books
  brand: Books
  search: false
  fluid: false
  menu:
    Home: /
    API (right):
      Books: /books
    Help:
      About: /about

api:
  /books: sql/books.sql

pages:
  /: sql/books.sql
  /about: ''
