server:
  port: ${PORT:9005}

spring:
  application:
    name: workflow-executor

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

functions:
  source:
    template: "template.vm"
  ignite:
      config: "cache.xml"