version: "2"

services:
  rethinkdb:
    image: rethinkdb:2.3.5
    volumes:
      - ./data/rethinkdb:/data
    networks:
      - squirrel

  # message bus
  rabbit:
    image: rabbitmq:management
    networks:
      - squirrel

  frontier:
    image: squirrel
    environment:
      HOBBIT_RABBIT_HOST: rabbit
      SEED_FILE: /var/squirrel/seeds/mCloudSeed.txt
      RDB_HOST_NAME: rethinkdb
      RDB_PORT: 28015
      SERVICE_PRECONDITION: "rethinkdb:28015 rabbit:5672"
    volumes:
      - ./data/frontier:/var/squirrel/data
      - ./seeds:/var/squirrel/seeds
    command: java -cp squirrel.jar org.hobbit.core.run.ComponentStarter org.aksw.simba.squirrel.components.FrontierComponent
    networks:
      - squirrel

  worker1:
    image: squirrel
    environment:
      HOBBIT_RABBIT_HOST: rabbit
      OUTPUT_FOLDER: /var/squirrel/data
      SERVICE_PRECONDITION: "rethinkdb:28015 rabbit:5672"
    volumes:
        - ./data/worker1:/var/squirrel/data
    command: java -cp squirrel.jar org.hobbit.core.run.ComponentStarter org.aksw.simba.squirrel.components.WorkerComponent
    networks:
      - squirrel

  worker2:
    image: squirrel
    environment:
      HOBBIT_RABBIT_HOST: rabbit
      OUTPUT_FOLDER: /var/squirrel/data
      SERVICE_PRECONDITION: "rethinkdb:28015 rabbit:5672"
    volumes:
        - ./data/worker2:/var/squirrel/data
    command: java -cp squirrel.jar org.hobbit.core.run.ComponentStarter org.aksw.simba.squirrel.components.WorkerComponent
    networks:
      - squirrel

  worker3:
    image: squirrel
    environment:
      HOBBIT_RABBIT_HOST: rabbit
      OUTPUT_FOLDER: /var/squirrel/data
      SERVICE_PRECONDITION: "rethinkdb:28015 rabbit:5672"
    volumes:
        - ./data/worker3:/var/squirrel/data
    command: java -cp squirrel.jar org.hobbit.core.run.ComponentStarter org.aksw.simba.squirrel.components.WorkerComponent
    networks:
      - squirrel

networks:
  squirrel:
    external:
      name: squirrel
