##############################################################
server:
  #配置网站根目录位置
  servlet-path: /

spring:
#  redis:
#    database: 0
#    host: h-redis
#    port: 6379
#    password: foobared
#    timeout: 0
#    pool:
#      max-active: 8
#      max-wait: -1
#      max-idle: 8
#      min-idle: 0
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://h-mysql:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password:
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    # useGlobalDataSourceStat: true # 合并多个DruidDataSource的监控数据
