##############################################################+
attach_path: ./attach/



server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

spring:
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: module-admin
  profiles:
    active: dev
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb
  thymeleaf:
    prefix: classpath:/templates/
    mode: LEGACYHTML5
    cache: false
    encoding: utf-8
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    time-zone: UTC

#############################################################################
#库表版本管理
flyway:
  enabled: true
  locations: classpath:/db
  baseline-on-migrate: true

mybatis:
  type-aliases-package: com.tangly.entity #指定bean所在包
  mapperLocations: classpath*:mapper/*.xml      #指定映射文件
  configuration:
    map-underscore-to-camel-case: true
    lazy-loading-enabled: true
    aggressive-lazy-loading: true
mapper:
  mappers: com.tangly.base.BaseMybatisMapper #mappers 多个接口时逗号隔开
  not-empty: false
  identity: MYSQL


#pagehelper
pagehelper:
  helperDialect: mysql
  #前后端分离时尽量关闭合理化功能false
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
