### Spring properties
# Service registers under this name
spring:
  application:
    name: open-ie-ms

# Discovery Server Access
eureka:
  instance:
    metadataMap:
      type: extractor
      friendlyname: OpenIE
    hostName: ${OPEN_IE_PUBLISH_HOST:localhost} 
    preferIpAddress: false 
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVICE_HOST:localhost}:${EUREKA_SERVICE_PORT:8761}/eureka/

# HTTP Server (Tomcat) Port
server: 
  port: ${OPEN_IE_PUBLISH_PORT:2226}

# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
error:
  whitelabel:
    enabled: false
