version: "3.5"
services:
  db:
    image: postgres:10-alpine
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
    environment:
      - POSTGRES_PASSWORD=postgres


  jqmbootstrap:
    # Create the database schema on startup and stops.
    build:
      context: .
    image: test:latest
    environment:
      - JQM_INIT_MODE=UPDATER
      - JQM_POOL_CONNSTR=jdbc:postgresql://db/postgres
      - JQM_POOL_VALIDATION_QUERY=SELECT version()
      - JQM_POOL_DRIVER=org.postgresql.Driver
      - JQM_POOL_USER=postgres
      - JQM_POOL_PASSWORD=postgres
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
      restart_policy: 
        condition: none

  jqmweb:
    build:
      context: .
    image: test:latest
    environment:
      - JQM_NODE_NAME=_localhost_
      - JQM_INIT_MODE=CLUSTER
      - JQM_CREATE_NODE_TEMPLATE=TEMPLATE_WEB
      - JQM_POOL_CONNSTR=jdbc:postgresql://db/postgres
      - JQM_POOL_VALIDATION_QUERY=SELECT version()
      - JQM_POOL_DRIVER=org.postgresql.Driver
      - JQM_POOL_USER=postgres
      - JQM_POOL_PASSWORD=postgres
    ports:
      - target: 1789
        published: 1789
        protocol: tcp
        mode: ingress
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
  
  jqmworker:
    build:
      context: .
    image: test:latest
    environment:
      - JQM_NODE_NAME=_localhost_
      - JQM_INIT_MODE=CLUSTER
      - JQM_CREATE_NODE_TEMPLATE=TEMPLATE_DRONE
      - JQM_POOL_CONNSTR=jdbc:postgresql://db/postgres
      - JQM_POOL_VALIDATION_QUERY=SELECT version()
      - JQM_POOL_DRIVER=org.postgresql.Driver
      - JQM_POOL_USER=postgres
      - JQM_POOL_PASSWORD=postgres
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: vip
