# Service registers under this name
# Control the InternalResourceViewResolver:
spring:
  application:
    name: webclient

# Discovery Server Access
eureka:
  instance:
    metadataMap:
      type: webclient
      friendlyname: Webclient
      instance:
    hostName: ${WEBCLIENT_PUBLISH_HOST:localhost} 
    preferIpAddress: false 
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVICE_HOST:localhost}:${EUREKA_SERVICE_PORT:8761}/eureka/


# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
error:
  whitelabel:
    enabled: false
    
#server port      
server:
  port: ${WEBCLIENT_PUBLISH_PORT:9090}

#zuul route
zuul:
  routes:
    chatbot:
      path: /CHATBOT/**
      serviceId: CHATBOT
    repo:
      path: /REPO-MS/**
      serviceId: REPO-MS
    executer:
      path: /EXECUTER-MS/**
      serviceId: EXECUTER-MS
    database:
      path: /DATABASE-MS/**
      serviceId: DATABASE-MS
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 10000

ribbon:
  eureka:
    enabled: true
    ReadTimeout: 20000
    ConnectTimeout: 20000