################################################################
#
# This is a file for local configurations of Kitodo Mediaserver
#
# Entries in this file override settings in default.yml
#
#################################################################

logging:
  path: /srv/kitodo/mediaserver/logs/

fileserver:
  rootUrl: http://localhost:8980/files/
  caching: true
  cachePath: /srv/kitodo/mediaserver/cache/

mets:
  originalFileGrpSuffix: PRESENTATION

importer:
  hotfolderPath: /srv/kitodo/mediaserver/hotfolder/
  importingFolderPath: /srv/kitodo/mediaserver/importing/
  tempWorkFolderPath: /srv/kitodo/mediaserver/import_temp/
  errorFolderPath: /srv/kitodo/mediaserver/import_error/
  workFilesPath: /srv/kitodo/mediaserver/files/
  cron: 0 0 * * * *

  validationFileGrps:
  - PRESENTATION
  - FULLTEXT

conversion:
  watermark:
    enabled: true
    renderMode: text
    textMode:
      content: "Example Text"
      font: "Arial"
      colorRGB: "34,65,255"
      size: 16
      gravity: "southwest"
      offsetX: 25
      offsetY: 0
    imageMode:
      path: /srv/kitodo/assets/watermark.png
      opacity: 75
      gravity: "southeast"
      offsetX: 50
      offsetY: 0
    extendCanvas:
      enabled: true
      backgroundColorRGB: "0,0,0"
      addX: 0
      addY: 25
