version: '2'

services:
  tomcat:
    image: tomcat:jre8
    restart: always
    ports:
      - "8180:8080"
    volume:
      - /DATA/playSpring/brige:/bridge
    depends_on:
      - mysql
      
  mysql:
    image: mysql:8
    restart: always
    volume:
      - /DATA/playSpring/mysql/db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: playSpring
      MYSQL_DATABASE: playSpring
      MYSQL_USER: playSpring
      MYSQL_PASSWORD: playSpring