[[_upgrade_adapters]]

It is important that you upgrade {project_name} server first, and then upgrade the adapters. Earlier versions of the
adapter might work with later versions of {project_name} server, but earlier versions of {project_name} server might not
work with later versions of the adapter.

[[_compatibility_with_older_adapters]]
== Compatibility with older adapters

As mentioned above, we try to support the newer version of {project_name} server to work with older version of the adapters.
However in some cases, we need to do fixes on the {project_name} server side, which may break compatibility with older version
of the adapters. For example when we implement some new aspects of the OpenID Connect specification, which older client adapter
is not aware off.

For those cases, we added Compatibility modes. For OpenId Connect clients, there is the section named `OpenID Connect Compatibility Modes` in
the {project_name} admin console on the page with client details. Here you can disable some new aspects of {project_name} server
to preserve compatibility with older client adapters. More details are available in the tooltips of individual switches.


[[_upgrade_eap_adapter]]
== Upgrading the EAP Adapter

To upgrade the {appserver_name} adapter, complete the following steps:

. Download the new adapter archive.
. Remove the previous adapter modules by deleting the `{appserver_dirref}/modules/system/add-ons/keycloak/` directory.
. Unzip the downloaded archive into {appserver_dirref}.


[[_upgrade_js_adapter]]
== Upgrading the JavaScript Adapter

To upgrade a JavaScript adapter that has been copied to your web application, complete the following steps: 

. Download the new adapter archive.
. Overwrite the keycloak.js file in your application with the keycloak.js file from the downloaded archive.


[[_upgrade_nodejs_adapter]]
== Upgrading the Node.js Adapter

To upgrade a Node.js adapter that has been copied to your web application, complete the following steps:

. Download the new adapter archive.
. Remove the existing Node.js adapter directory
. Unzip the updated file into its place
. Change the dependency for keycloak-connect in the package.json of your application
