### Spring properties
# Service registers under this name
spring:
  application:
    name: fred-ms

# Discovery Server Access
eureka:
  instance:
    metadataMap:
      type: extractor
      friendlyname: Fred
    hostName: ${FRED_PUBLISH_HOST:localhost} 
    preferIpAddress: false 
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVICE_HOST:localhost}:${EUREKA_SERVICE_PORT:8761}/eureka/

# HTTP Server (Tomcat) Port
server: 
  port: ${FRED_PUBLISH_PORT:2223}

# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
error:
  whitelabel:
    enabled: false
