version: '2'
services:

  postgresql:
      hostname: postgres
      image: 'postgres'
      ports:
        - '15432:15432'
      environment:
        POSTGRES_PASSWORD: swarm
        POSTGRES_USER: swarm
        POSTGRES_DB: test
        PGPORT: 15432
