version: '3'

volumes:
    broker_1: {}
    broker_2: {}
    broker_3: {}

services:

    broker-1:
        image: camunda/zeebe:${ZEEBE_VERSION:-latest}
        ports:
            - 51015:51015
        environment:
            - ZEEBE_LOG_LEVEL=${ZEEBE_LOG_LEVEL:-debug}
            - BOOTSTRAP=3
        volumes:
            - broker_1:/usr/local/zeebe/data

    broker-2:
        image: camunda/zeebe:${ZEEBE_VERSION:-latest}
        ports:
            - 51016:51015
        environment:
            - ZEEBE_LOG_LEVEL=${ZEEBE_LOG_LEVEL:-debug}
            - INITIAL_CONTACT_POINT=broker-1:51016
            - BOOTSTRAP=0
        volumes:
            - broker_2:/usr/local/zeebe/data

    broker-3:
        image: camunda/zeebe:${ZEEBE_VERSION:-latest}
        ports:
            - 51017:51015
        environment:
            - ZEEBE_LOG_LEVEL=${ZEEBE_LOG_LEVEL:-debug}
            - INITIAL_CONTACT_POINT=broker-1:51016
            - BOOTSTRAP=0
        volumes:
            - broker_3:/usr/local/zeebe/data
